---

kafka_link: http://ftp.unicamp.br/pub/apache/kafka/2.2.0/kafka_2.12-2.2.0.tgz
path_kafka: /etc/kafka
user_kafka: kafka
version_kafka: 2.2.0
version_kafka_release: 2.12
port_kafka: 9092
num_partition: 1
num_threads: 8
default_replication: 1
offset_topic_replication: 1
log_dir_kafka: /var/log/kafka
pass_key_kafka: kafkapass
log_retention_hours: 60
enable_zoo_connect: true
zoo_host_server: "{{ private_ip_zookeeper }}"
zoo_port_server: 2181
client_port_zoo: 2181
xms_limit: 512m
xmx_limit: 1g
data_dir_zoo: /var/lib/zookeeper
port_exp_prom: 7072
