---

- name: create prometheus group
  group:
    name: "{{ prometheus_group }}"
    state: present
  become: true

- name: create prometheus user
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    createhome: no
    shell: /sbin/nologin
    state: present
  become: true

- name: create prometheus installation directory
  file:
    path: "{{ prometheus_install_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o=rx"
  become: true

- name: download and untar prometheus
  unarchive:
    src: "{{ prometheus_url }}"
    dest: "{{ prometheus_install_path }}"
    remote_src: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  become: true

- name: create prometheus server directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o=rx"
  with_items:
    - "{{ prometheus_config_path }}"
    - "{{ prometheus_db_path }}"
    - "{{ prometheus_rule_path }}"
  become: true

- name: copy prometheus main config file
  template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_path }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  become: true

- name: copy prometheus rules file
  copy:
    src: "rules.yml"
    dest: "{{ prometheus_rule_path }}/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  become: true

- name: copy prometheus systemd config to server
  template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
    mode: "a+x"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  become: true
  notify:
    - start prometheus
